config/routes.rb
Rails.application.routes.draw do
  resources :tv_series
  

   root 'tv_series#index'

     get 'add_date/:id' => 'tv_series#add_date'

end

app/models/tv_series.rb
class TvSeries < ActiveRecord::Base
	validates :name, :season, :episode, presence: true
	validates :season, :episode, :numericality => { :greater_than => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tv_series_controller.rb
class TvSeriesController < ApplicationController
  before_action :set_tv_series, only: [:show, :edit, :update, :destroy, :add_date]

  def add_date
    
  end

  # GET /tv_series
  # GET /tv_series.json
  def index
    @tv_series = TvSeries.all
  end

  # GET /tv_series/1
  # GET /tv_series/1.json
  def show
  end

  # GET /tv_series/new
  def new
    @tv_series = TvSeries.new
  end

  # GET /tv_series/1/edit
  def edit
  end

  # POST /tv_series
  # POST /tv_series.json
  def create
    @tv_series = TvSeries.new(tv_series_params)

    respond_to do |format|
      if @tv_series.save
        format.html { redirect_to @tv_series, notice: 'Tv series was successfully created.' }
        format.json { render :show, status: :created, location: @tv_series }
      else
        format.html { render :new }
        format.json { render json: @tv_series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_series/1
  # PATCH/PUT /tv_series/1.json
  def update
    respond_to do |format|
      if @tv_series.update(tv_series_params)
        format.html { redirect_to @tv_series, notice: 'Tv series was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_series }
      else
        format.html { render :edit }
        format.json { render json: @tv_series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_series/1
  # DELETE /tv_series/1.json
  def destroy
    @tv_series.destroy
    respond_to do |format|
      format.html { redirect_to tv_series_index_url, notice: 'Tv series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_series
      @tv_series = TvSeries.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_series_params
      params.fetch(:tv_series, {}).permit(:name, :season, :episode, :next_episode_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_series_helper.rb
module TvSeriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tvseries" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Tvseries', tv_series_index_path, class: "navbar-brand" %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; <%= link_to 'Павел Кравченя', 'mailto:drumbron@icloud.com' %> <%=Date.today.year%></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/tv_series/_form.html.erb
<%= simple_form_for(@tv_series) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name, placeholder: 'Название сериала' %>
  	<%= f.input :season %>
  	<%= f.input :episode %>
  	<%= f.input :next_episode_date, :as => :date_picker, placeholder: 'Выбери дату, нажав на кнопку справа' %>
    <p class="field-tip"><%= 'Если дата совсем неизвестна, оставь поле пустым' %></p>
    <p class="field-tip"><%= 'Если точная дата неизвестна, но ты точно знаешь месяц, укажи первый день месяца, например 01.05.2016' %></p>
    <p class="field-tip"><%= 'Если точная дата неизвестна, но ты точно знаешь время года, укажи первый день времени года, например 01.09.2016' %></p>
    <p class="field-tip"><%= 'Если точная дата неизвестна, но ты точно знаешь год, укажи первый день года, например 01.01.2016' %></p>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: 'Сохранить' %>
  </div>
<% end %>

app/views/tv_series/add_date.html.erb
<h1>Добавить дату к сериалу <%=@tv_series.name%></h1>

<%='тут типа поле даты'%>

app/views/tv_series/edit.html.erb
<h1>Изменить сериал "<%= @tv_series.name %>"</h1>

<%= render 'form' %>

<%= link_to @tv_series.name, @tv_series %> |
<%= link_to 'На главную', tv_series_index_path %>

app/views/tv_series/index.html.erb
<h1>Список твоих сериалов</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Сериал</th>
      <th>Сезон</th>
      <th>Серия</th>
      <th>Дата выхода серии</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <!-- сортировка с учетом nil - магия, которую я не совсем понял -->
    <% @sorted_tv_series = @tv_series.sort_by {|tv_series| [tv_series.next_episode_date ? 0 : 1, tv_series.next_episode_date || 0]} %> 
    <% @counter = 1 %>
    <% @sorted_tv_series.each do |tv_series| %>
      <% if tv_series.next_episode_date && tv_series.next_episode_date < Date.today %>
        <tr class="time-to-watch">
      <% elsif tv_series.next_episode_date && tv_series.next_episode_date == Date.today %>
        <tr class="time-to-watch-on-tv">
      <% else %>
        <tr>
      <% end %>
          <td><%= @counter %></td>
          <td><%= link_to tv_series.name, tv_series %></td>
          <td><%= tv_series.season %></td>
          <td><%= tv_series.episode %></td>
          <% @name = tv_series.name.gsub(' ', '%20') %>
          <% if (tv_series.next_episode_date) %>
            <td><%= link_to tv_series.next_episode_date.strftime('%d.%m.%Y'), 'https://en.wikipedia.org/wiki/' + @name, target: '_blank' %><br><%= link_to 'Дата неверна?', edit_tv_series_path(tv_series) %></td>
          <% else %>
            <td><%= link_to 'Неизвестно', 'https://en.wikipedia.org/wiki/' + @name, target: '_blank' %>.<br><%= link_to 'Указать дату', edit_tv_series_path(tv_series) %></td>
          <% end %>
          <% @season = tv_series.season < 10 ? '0' + tv_series.season.to_s : tv_series.season.to_s %>
          <% @episode = tv_series.episode < 10 ? '0' + tv_series.episode.to_s : tv_series.episode.to_s %>
          <% if(tv_series.next_episode_date && tv_series.next_episode_date < Time.now) %>
            <td><%= link_to 'Субтитры', 'http://www.opensubtitles.org/en/search2/sublanguageid-eng/moviename-' + @name + '+s' + @season + 'e' + @episode, target: '_blank' %></td>
            <td><%= link_to 'Torrent', 'https://kat.cr/usearch/' + @name + '%20s' + @season + 'e' + @episode + '%20720p/', target: '_blank' %></td>
            <td><%= link_to 'Я посмотрел серию', tv_series_path(tv_series, tv_series: {episode: tv_series.episode + 1, next_episode_date: tv_series.next_episode_date + 1.week}), method: :patch, data: {confirm: 'Точно посмотрел?'} %><br>
            <%= link_to 'Я посмотрел сезон', tv_series_path(tv_series, tv_series: {season: tv_series.season + 1, episode: 1, next_episode_date: nil}), method: :patch, data: {confirm: 'Целый сезон?'} %></td>
          <% else %>
            <td colspan="3">Серия ещё не вышла</td>
          <% end %>
          <td><%= link_to 'Изменить', edit_tv_series_path(tv_series) %></td>
          <td><%= link_to 'Удалить', tv_series, method: :delete, data: {confirm: 'Надоело?'} %></td>
        </tr>
      <% @counter = @counter + 1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить сериал', new_tv_series_path %>

app/views/tv_series/new.html.erb
<h1>Добавить сериал</h1>

<%= render 'form' %>

<%= link_to 'Назад', tv_series_index_path %>

app/views/tv_series/show.html.erb
<h1><%= @tv_series.name %></h1>

<table class="table">
<tr><td>Ты будешь смотреть <%= @tv_series.episode %> серию <%= @tv_series.season %> сезона</td></tr>
<% @name = @tv_series.name.gsub(' ', '%20') %>
<% if (@tv_series.next_episode_date) %>
	<tr><td><%= link_to @tv_series.next_episode_date.strftime('%d.%m.%Y'), 'https://en.wikipedia.org/wiki/' + @name, target: '_blank' %>. <%= link_to 'Дата неверна?', edit_tv_series_path(@tv_series) %></td></tr>
<% else %>
	<tr><td>Дата выхода серии <%= link_to 'неизвестна', 'https://en.wikipedia.org/wiki/' + @name, target: '_blank' %>. <%= link_to 'Указать дату', edit_tv_series_path(@tv_series) %></td></tr>
<% end %>
<% @season = @tv_series.season < 10 ? '0' + @tv_series.season.to_s : @tv_series.season.to_s %>
<% @episode = @tv_series.episode < 10 ? '0' + @tv_series.episode.to_s : @tv_series.episode.to_s %>
<% if(@tv_series.next_episode_date && @tv_series.next_episode_date < Time.now) %>
	<tr><td><%= link_to 'Найти субтитры', 'http://www.opensubtitles.org/en/search2/sublanguageid-eng/moviename-' + @name + '+s' + @season + 'e' + @episode, target: '_blank' %></td></tr>
	<tr><td><%= link_to 'Найти torrent', 'https://kat.cr/usearch/' + @name + '%20s' + @season + 'e' + @episode + '%20720p/', target: '_blank' %></td></tr>
	<tr><td><%= link_to 'Я посмотрел серию', tv_series_path(@tv_series, tv_series: {episode: @tv_series.episode + 1, next_episode_date: @tv_series.next_episode_date + 1.week}), method: :patch, data: {confirm: 'Точно посмотрел?'} %></td></tr>
	<tr><td><%= link_to 'Я посмотрел сезон', tv_series_path(@tv_series, tv_series: {season: @tv_series.season + 1, episode: 1, next_episode_date: nil}), method: :patch, data: {confirm: 'Целый сезон?'} %></td></tr>
<% end %>
<tr><td><%= link_to 'Изменить сериал', edit_tv_series_path(@tv_series) %></td></tr>
<tr><td><%= link_to 'Удалить сериал', @tv_series, method: :delete, data: {confirm: 'Надоело?'} %></td></tr>
</table>

<%= link_to 'Назад', tv_series_index_path %>